/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:d4d1eadf-dbec-4e5a-84e1-9d02d3477d87",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_5kkJEmA2A",
    "aws_user_pools_web_client_id": "51ogbicosgln7a4pn9jf6l6d96",
    "oauth": {}
};


export default awsmobile;
